version: "3"

services:
  postgres:
    image: "postgres:14.3"
    hostname: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_ROOT_PASSWORD: root123
      POSTGRES_PASSWORD: root123
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  app:
    depends_on:
      - "postgres"
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/ror-file-system
      - gems:/gems

volumes:
  postgres:
  gems: